# you can update these variables based on your own environment
base_dir: "{{ playbook_dir | dirname }}"
dest_dir: "/home/prometheus"
home_dir: "{{ dest_dir }}/prometheus"
compose_file: "{{ home_dir }}/docker/prometheus.yml"
